name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre-commit:
    name: Pre-commit, Migrations, and Tests
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run Pre-commit
        run: |
          uv sync --group test
          uv run pre-commit run --all-files
